// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InfrastructureService.Domain;

public partial class Message
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string MessageContent { get; set; }

    public DateTime? SentAt { get; set; }

    public Guid? Status { get; set; }

    public virtual MessagesStatus StatusNavigation { get; set; }

    public virtual User User { get; set; }
}