// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InfrastructureService.DBModels;

public partial class Notification
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string Type { get; set; }

    public string Content { get; set; }

    public DateTime? SentAt { get; set; }

    public virtual User User { get; set; }
}