// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InfrastructureService.DBModels;

[Table("WhatsAppMessagesStatus")]
public partial class WhatsAppMessagesStatus
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SentAt { get; set; }

    [InverseProperty("StatusNavigation")]
    public virtual ICollection<WhatsAppMessage> WhatsAppMessages { get; set; } = new List<WhatsAppMessage>();
}