// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InfrastructureService.DBModels;

public partial class WhatsAppMessage
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string MessageContent { get; set; }

    public DateTime? SentAt { get; set; }

    public Guid? Status { get; set; }

    public virtual WhatsAppMessagesStatus StatusNavigation { get; set; }

    public virtual User User { get; set; }
}