// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InfrastructureService.DBModels;

public partial class WhatsAppMessage
{
    [Key]
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    [Required]
    public string MessageContent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SentAt { get; set; }

    public Guid? Status { get; set; }

    [ForeignKey("Status")]
    [InverseProperty("WhatsAppMessages")]
    public virtual WhatsAppMessagesStatus StatusNavigation { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("WhatsAppMessages")]
    public virtual User User { get; set; }
}